export const ADD_RESERVATION = 'ADD_RESERVATION';
export const CANCEL_RESERVATION = 'CANCEL_RESERVATION';
export const EMPTY_RESERVATIONS = 'EMPTY_RESERVATIONS';
export const FETCH_HOTELS_PENDING = 'FETCH_HOTELS_PENDING';
export const FETCH_HOTELS_SUCCESS = 'FETCH_HOTELS_SUCCESS';
export const FETCH_HOTELS_ERROR = 'FETCH_HOTELS_ERROR';

